name: m3care
channels:
- conda-forge
- pytorch
- nvidia
dependencies:
- python>=3.8
- pytorch>=2.4, <2.5
- torchvision
- torchaudio
- pytorch-cuda=11.8
- numpy>=2.1, <2.2
- ipykernel
- jupyter
- tensorboard
- pip
- pip:
    - torcheval
    - torchtyping